### PR TITLE
chore: update Fedora image

### PR DESCRIPTION
**Pull request by ahsan-z-khan**
Signed-off-by: Ahsan Khan <amzahsa@amazon.com>

Issue #, if available:

*Description of changes:*
Updated Fedora OS image to the latest version to address security vulnerabilities. 

*Testing done:*
`make test-e2e`

- [x] I've reviewed the guidance in CONTRIBUTING.md

#### License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by pendo324** [comment]
LGTM, thanks

**Comment by ningziwen** [comment]
Why is this a breaking change? Any existing E2E tests failed?

**Comment by pendo324** [comment]
Good point @ningziwen, it shouldn't be a breaking change. @ahsan-z-khan, please change the title to remove the `!` before merging.

**Comment by ahsan-z-khan** [comment]
`finch cp` tests failing for me locally. Don't merge it yet. I'll update on it. Testing manually on a container

**Comment by pendo324** [comment]
> `finch cp` tests failing for me locally. Don't merge it yet. I'll update on it. Testing manually on a container

fwiw, all the tests passed on my system (Intel 12.6.2)

**Comment by ahsan-z-khan** [comment]
okay

> > `finch cp` tests failing for me locally. Don't merge it yet. I'll update on it. Testing manually on a container
> 
> fwiw, all the tests passed on my system (Intel 12.6.2)

Okay let's merge then? Might be an issue with my local setup.

**Review by pendo324 — APPROVED** [review]

**Pull request merged**
